version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${VITE_DB_USER}
      POSTGRES_PASSWORD: ${VITE_DB_PASS}
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
volumes:
  postgres_data: